### PR TITLE
Send original event.

### PR DESCRIPTION
**Pull request by kabudahab**

### CODE REVIEW

**Comment by dy** [comment]
It works only for the wheel listener, but not for pinch/move - I was trying to do that not once.
The impetus and touch-pinch don't expose event afaik, so it either needs to be fake or lobby PRs somehow.

**Comment by kabudahab** [comment]
This sends the original event of the wheel listener and can be used to detect whether Ctlr key is down when scrolling.  At the moment, `event` is `undefined` for all events.

**Comment by dy** [comment]
This event property is inconsistent for `pinch`/`move`, needs to be added for them too.

**Comment by kabudahab** [comment]
Inconsistent event property is better than `undefined`. I am happy with how it works now, so I will close.

**Comment by dy** [comment]
Just for the reference https://github.com/dy/pan-zoom/pull/17, https://github.com/dy/pan-zoom/issues/18.
I suppose it may be updated from impetus/touch-pinch to something new.

**Pull request closed without merging**
